name: ci

on: [push]

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly
      - name: Run Tests
        run: forge test -vvv

  forge-snapshot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly
      - name: Install deps
        run: forge install
      - name: Check contract sizes
        run: forge build --sizes
      - name: Check gas snapshots
        run: forge snapshot --check

  huff-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly
      - name: Run Huff Tests
        uses: cheethas/huff-tests-action@v2
        with:
          with-forge-tests: false
          test-extension: ".t.huff"

  forge-scripts:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Huff
        uses: huff-language/huff-toolchain@v2
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true
      - name: Run scripts
        run: |
          ls -lsa
          ls script/
          for file in script/*; do
            forge script $file -vvvv
          done

  cargo-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: cargo test
        run: cargo test --all --all-features

  cargo-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: cargo clippy
        run: cargo +nightly clippy --all --all-features -- -D warnings

  cargo-build:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ./bot
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: build
        id: build
        continue-on-error: true
        run: cargo +nightly build --all
